import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const panelSource = readFileSync(new URL('../src/components/DraggablePanel.tsx', import.meta.url), 'utf8');
const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const typesSource = readFileSync(new URL('../src/types.ts', import.meta.url), 'utf8');
const videoBackgroundSource = readFileSync(new URL('../src/components/VideoBackground.tsx', import.meta.url), 'utf8');

test('control panel is split into basic and advanced tabs', () => {
  assert.match(panelSource, /activeTab/);
  assert.match(panelSource, /'basic'/);
  assert.match(panelSource, /'advanced'/);
  assert.match(panelSource, /GSDF-QC 全域測試圖/);
  assert.match(panelSource, /FullDiagnosticPattern/);
  assert.match(panelSource, /InspectionModeView/);
  assert.match(panelSource, /InspectionModeHeader/);
  assert.match(panelSource, /InspectionMode = 'pattern' \| 'chart' \| null/);
  assert.match(panelSource, /inspectionMode \?/);
  assert.match(panelSource, /setInspectionMode\('chart'\)/);
  assert.match(panelSource, /setInspectionMode\(null\)/);
  assert.match(panelSource, /PanelTabSwitch/);
  assert.match(panelSource, /PanelLayoutModeSwitch/);
  assert.match(panelSource, /grid h-8 w-\[96px\]/);
  assert.match(panelSource, /panelMode === 'c' \? '' : 'space-y-3'/);
  assert.match(panelSource, /panelMode === 'c' \? 'gsdf-header-controls' : ''/);
  assert.match(panelSource, /<PanelLayoutModeSwitch value=\{panelMode\} onChange=\{selectPanelMode\} \/>/);
  assert.match(panelSource, /<PanelLayoutModeSwitch value=\{panelMode\} onChange=\{selectPanelMode\} \/>[\s\S]*title="關閉面板"/);
  assert.match(panelSource, /PANEL_MODE_OPTIONS/);
  assert.match(panelSource, /GSDF_PANEL_MODE_CHANGED/);
  assert.match(panelSource, /panelMode === 'b'/);
  assert.match(panelSource, /panelMode === 'c'/);
  assert.match(panelSource, /C_PANEL_DEFAULT_CONTROL_WIDTH = 300/);
  assert.match(panelSource, /C_PANEL_MIN_CONTROL_WIDTH = 260/);
  assert.match(panelSource, /C_PANEL_MAX_CONTROL_WIDTH = 420/);
  assert.match(panelSource, /gridTemplateColumns: `\$\{cControlWidth\}px 12px minmax\(0,1fr\)`/);
  assert.match(panelSource, /gsdf-column-resize-handle/);
  assert.match(panelSource, /aria-label="調整左側面板寬度"/);
  assert.match(panelSource, /handleCColumnResizePointerDown/);
  assert.match(panelSource, /handleCColumnResizePointerMove/);
  assert.match(panelSource, /handleCColumnResizePointerUp/);
  assert.match(panelSource, /space-y-4 overflow-y-auto overflow-x-hidden/);
  assert.match(panelSource, /CenterWorkspaceMode = 'pattern' \| 'chart' \| 'both'/);
  assert.match(panelSource, /role="tablist"/);
  assert.match(panelSource, /role="tab"/);
  assert.match(panelSource, /const selected = value === tab/);
  assert.match(panelSource, /aria-selected=\{selected\}/);
  assert.match(panelSource, /style=\{selected \? \{ color: panelTheme === 'light' \? '#f8fafc' : '#111418' \} : undefined\}/);
  assert.match(panelSource, /gsdf-header-controls/);
  assert.match(panelSource, /gsdf-header-controls flex shrink-0 flex-wrap items-center justify-end gap-2/);
  assert.match(panelSource, /panelMode !== 'c' && <div className="gsdf-header-controls flex shrink-0 flex-wrap items-center justify-end gap-2"/);
  assert.match(panelSource, /gsdf-status-inline-metrics/);
  assert.match(panelSource, /flex min-w-0 flex-wrap items-center justify-start gap-1\.5/);
  assert.doesNotMatch(panelSource, /grid grid-cols-4 gap-1\.5/);
  assert.match(panelSource, /目標值非實際測/);
  assert.match(panelSource, /text-\[24px\]/);
  assert.match(panelSource, /justify-center gap-1 rounded-md border px-2 text-\[10px\]/);
  assert.match(panelSource, /效果開啟/);
  assert.match(panelSource, /效果關閉/);
  assert.match(panelSource, /drawDiagnosticPattern/);
  assert.match(panelSource, /drawLinePairBand/);
  assert.match(panelSource, /drawVerticalGradient/);
  assert.match(panelSource, /drawContinuousSweepCell/);
  assert.match(panelSource, /line-pair and gradient pattern/);
  assert.match(panelSource, /Grid3X3/);
  assert.match(panelSource, /GSDF_PATTERN_VIEW_CHANGED/);
  assert.match(panelSource, /PANEL_THEME_STORAGE_KEY/);
  assert.match(panelSource, /theme-\$\{panelTheme\}/);
  assert.match(panelSource, /切換到明亮面板/);
  assert.match(panelSource, /關閉面板/);
  assert.match(panelSource, /panelClosed/);
  assert.match(panelSource, /handlePanelClose/);
  assert.match(panelSource, /setPanelClosed\(true\)/);
  assert.match(panelSource, /Filter 總量/);
  assert.match(panelSource, /Gamma 補償/);
  assert.match(panelSource, /gammaTarget/);
  assert.match(panelSource, /gammaCorrectionToTarget/);
  assert.match(panelSource, /gammaTargetToCorrection/);
  assert.match(panelSource, /DEFAULT_GAMMA_TARGET/);
  assert.match(panelSource, /gsdf-lmax-range-row/);
  assert.match(panelSource, /className="gsdf-range w-full"/);
  assert.match(panelSource, /色彩模型/);
  assert.match(panelSource, /YCbCr/);
  assert.match(panelSource, /白點/);
  assert.match(panelSource, /飽和度/);
  assert.match(panelSource, /色調/);
  assert.match(panelSource, /maxLabel="50"/);
  assert.match(panelSource, /max=\{50\}/);
  assert.match(panelSource, /maxLabel="125"/);
  assert.match(panelSource, /max=\{125\}/);
  assert.match(panelSource, /minLabel="-30"/);
  assert.match(panelSource, /maxLabel="\+30"/);
  assert.match(panelSource, /min=\{-30\}/);
  assert.match(panelSource, /max=\{30\}/);
  assert.equal((panelSource.match(/grid grid-cols-2 gap-3 transition-opacity/g) ?? []).length, 1);
  assert.match(panelSource, /Palette/);
  assert.match(panelSource, /完整圖表/);
  assert.match(panelSource, /即時對比度分析視圖/);
  assert.match(panelSource, /中央視圖/);
  assert.match(panelSource, /C\+D/);
  assert.match(panelSource, /centerMode === 'both' \? 'grid grid-cols-2' : 'block'/);
  assert.match(panelSource, /EffectSwitch/);
  assert.match(panelSource, /role="switch"/);
  assert.match(panelSource, /aria-checked=\{enabled\}/);
  assert.match(panelSource, /啟動 EOTF 修正/);
  assert.match(panelSource, /效果應用/);
  assert.match(panelSource, /title="關閉"/);
  assert.match(panelSource, /gsdf-resize-grip/);
  assert.match(panelSource, /拖曳調整視圖大小/);
  assert.match(panelSource, /PanelBorderResizeHandles/);
  assert.match(panelSource, /data-resize-handle="e"/);
  assert.match(panelSource, /data-resize-handle="s"/);
  assert.match(panelSource, /data-resize-handle="se"/);
  assert.match(panelSource, /getResizeDeltas/);
  assert.match(panelSource, /standalonePanelSize/);
  assert.match(panelSource, /PANEL_MODE_SIZE/);
  assert.match(panelSource, /onExtensionResize\?\.\(deltaWidth, deltaHeight\)/);
  assert.match(panelSource, /standaloneInspectionSize/);
  assert.match(panelSource, /INSPECTION_MIN_WIDTH/);
  assert.match(panelSource, /INSPECTION_MIN_HEIGHT/);
  assert.match(appSource, /GSDF_PANEL_RESIZED/);
  assert.match(panelSource, /h-screen w-screen/);
  assert.match(panelSource, /cursor-nwse-resize/);
  assert.match(panelSource, /hidden=\{activeTab !== 'basic'\}/);
  assert.match(panelSource, /hidden=\{activeTab !== 'advanced'\}/);
  assert.match(panelSource, /DEFAULT_TARGET_LUMINANCE_NITS/);
  assert.match(panelSource, /完整 GSDF table 先算出來/);
  assert.match(panelSource, /React\.lazy/);
  assert.match(panelSource, /React\.Suspense/);
  assert.match(panelSource, /import\('\.\/GSDFChart'\)/);
  assert.match(panelSource, /disabled=\{disabled\}/);
  assert.match(panelSource, /aria-disabled=\{disabled\}/);
  assert.doesNotMatch(panelSource, /import \{ GSDFChart \} from '\.\/GSDFChart'/);
  assert.doesNotMatch(panelSource, /純 GSDF/);
  assert.doesNotMatch(panelSource, /曲線模式/);
  assert.match(panelSource, /GSDFStripeTest/);
  assert.match(panelSource, /GSDF 條紋測試/);
  assert.match(panelSource, /輸出預覽/);
  assert.match(panelSource, /亮度校準/);
  assert.match(panelSource, /完整多頻率條紋圖/);
  assert.match(panelSource, /renderBasicPanel\(false\)/);
  assert.doesNotMatch(panelSource, /grid-cols-\[300px_minmax\(0,1fr\)_300px\]/);
  assert.doesNotMatch(panelSource, /grid grid-rows-2/);
  assert.doesNotMatch(panelSource, /Transfer curve preview/);
  assert.doesNotMatch(panelSource, /active table/);
  assert.doesNotMatch(panelSource, /白位/);
  assert.doesNotMatch(panelSource, /onSaveDefault/);
  assert.doesNotMatch(panelSource, /儲存預設偏好設定/);
  assert.doesNotMatch(panelSource, /Math\.round\(\(viewport\.width - width\) \/ 2\)/);
  assert.doesNotMatch(panelSource, /FloatingOverlayWindow/);
  assert.doesNotMatch(panelSource, /gsdf-tab-bar grid grid-cols-2/);
  assert.doesNotMatch(panelSource, /\{extensionMode && \(/);

  const basicIndex = panelSource.indexOf("activeTab !== 'basic'");
  const advancedIndex = panelSource.indexOf("activeTab !== 'advanced'");
  assert.ok(basicIndex >= 0 && advancedIndex > basicIndex);
});

test('inspection modes use an inset hairline frame and lighter UI typography', () => {
  const cssSource = readFileSync(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(cssSource, /\.gsdf-inspection-mode::after/);
  assert.match(cssSource, /\.gsdf-inspection-header/);
  assert.match(cssSource, /inset: 2px/);
  assert.match(cssSource, /border: 1px solid rgba\(255, 255, 255, 0\.72\)/);
  assert.match(cssSource, /pointer-events: none/);
  assert.match(cssSource, /border-color: rgba\(148, 163, 184, 0\.09\)/);
  assert.match(cssSource, /font-weight: 500 !important/);
  assert.match(cssSource, /font-weight: 520/);
  assert.match(cssSource, /\.gsdf-header-controls/);
  assert.match(cssSource, /\.gsdf-range::-webkit-slider-thumb \{\s*width: 12px;\s*height: 18px;/);
  assert.match(cssSource, /\.gsdf-range::-moz-range-thumb \{\s*width: 12px;\s*height: 18px;/);
  assert.match(cssSource, /\.gsdf-tab-switch/);
  assert.match(cssSource, /\.gsdf-resize-edge/);
  assert.match(cssSource, /touch-action: manipulation/);
  assert.match(cssSource, /touch-action: none/);
  assert.doesNotMatch(cssSource, /font-weight: 650/);
  assert.doesNotMatch(cssSource, /gsdf-floating-window/);
});

test('header drag handling does not intercept interactive controls', () => {
  assert.match(panelSource, /function isInteractiveDragTarget/);
  assert.match(panelSource, /button, input, label, select, textarea, a/);
  assert.match(panelSource, /data-no-drag/);
  assert.match(panelSource, /isInteractiveDragTarget\(e\.target\)/);
  assert.match(panelSource, /trySetPointerCapture/);
  assert.match(panelSource, /tryReleasePointerCapture/);
  assert.match(panelSource, /dragStartRef\.current\.pointerId !== e\.pointerId/);
  assert.match(panelSource, /resizeStartRef\.current\.pointerId !== e\.pointerId/);
  assert.match(panelSource, /onExtensionDrag\?\.\(deltaX, deltaY\)/);
  assert.match(panelSource, /dragHandlers=\{dragHandlers\}/);
  assert.match(panelSource, /resizeHandlers=\{resizeHandlers\}/);
  assert.match(appSource, /type: 'GSDF_CLOSE_PANEL'/);
  assert.match(appSource, /type: 'GSDF_PANEL_RESIZED'/);
});

test('standalone video preview uses the shared GSDF table model', () => {
  assert.match(videoBackgroundSource, /buildGsdfTableValues\(settings\)/);
  assert.match(videoBackgroundSource, /tableValues=\{gsdfTableValues\}/);
  assert.match(videoBackgroundSource, /eotf-ycbcr/);
  assert.match(videoBackgroundSource, /eotf-color/);
  assert.match(videoBackgroundSource, /hueRotate/);
  assert.match(videoBackgroundSource, /settings\.saturation/);
  assert.match(videoBackgroundSource, /Math\.min\(1\.25, settings\.saturation \/ 100\)/);
  assert.match(videoBackgroundSource, /Math\.max\(-30, Math\.min\(30, settings\.hue\)\)/);
  assert.match(videoBackgroundSource, /settings\.colorModel === 'ycbcr'/);
  assert.doesNotMatch(videoBackgroundSource, /type="gamma"/);
});

test('analysis chart resizes with the control panel', () => {
  const chartSource = readFileSync(new URL('../src/components/GSDFChart.tsx', import.meta.url), 'utf8');

  assert.match(chartSource, /ResizeObserver/);
  assert.match(chartSource, /chartSize\.width/);
  assert.match(chartSource, /className = 'h-48'/);
  assert.doesNotMatch(chartSource, /width=\{291\}/);
});

test('diagnostic pattern follows the active transfer table', () => {
  assert.match(panelSource, /buildGsdfStripeRows\(settings\)/);
  assert.match(panelSource, /drawContinuousSweepCell/);
  assert.match(panelSource, /modulationPeriods = \[18, 12, 6, 4\]/);
  assert.match(panelSource, /rowCount = 18/);
  assert.match(typesSource, /const transferTable = buildGsdfTableValues\(normalized\)/);
  assert.match(typesSource, /getGammaAdjustedInputLevel/);
  assert.match(typesSource, /gammaLevel = getGammaAdjustedInputLevel\(inputLevel, normalized\.gammaTarget\)/);
  assert.match(typesSource, /gammaCorrectionToTarget/);
  assert.match(typesSource, /gammaTargetToCorrection/);
  assert.match(typesSource, /sampleTableValue\(transferTable, baseRatio\)/);
  assert.match(typesSource, /sampleTableValue\(transferTable, nextRatio\)/);
});

test('extension panel avoids internal scrollbars in the compact control view', () => {
  assert.match(panelSource, /h-\[720px\]/);
  assert.match(panelSource, /PANEL_DEFAULT_HEIGHT = 690/);
  assert.match(panelSource, /PANEL_EXPANDED_DEFAULT_HEIGHT = 720/);
  assert.match(panelSource, /a: \{ width: 420, minWidth: 380 \}/);
  assert.match(panelSource, /overflow-y-auto overflow-x-hidden p-4/);
  assert.doesNotMatch(panelSource, /flex-1 space-y-5 overflow-y-auto p-5/);
});

test('settings autosave one second after panel adjustments', () => {
  assert.match(appSource, /window\.setTimeout/);
  assert.match(appSource, /}, 1000\)/);
  assert.match(appSource, /gsdf_extension_settings/);
  assert.match(appSource, /偏好設定已自動儲存/);
  assert.doesNotMatch(appSource, /handleSaveDefault/);
});
