import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { test } from 'node:test';

const panelSource = readFileSync(new URL('../src/components/DraggablePanel.tsx', import.meta.url), 'utf8');
const appSource = readFileSync(new URL('../src/App.tsx', import.meta.url), 'utf8');
const typesSource = readFileSync(new URL('../src/types.ts', import.meta.url), 'utf8');
const videoBackgroundSource = readFileSync(new URL('../src/components/VideoBackground.tsx', import.meta.url), 'utf8');
const contentSource = readFileSync(new URL('../extension/content.js', import.meta.url), 'utf8');
const diagnosticProbeSource = readFileSync(new URL('../src/components/DiagnosticCameraProbe.tsx', import.meta.url), 'utf8');
const chartSource = readFileSync(new URL('../src/components/GSDFChart.tsx', import.meta.url), 'utf8');
const hard8ReferenceSource = readFileSync(new URL('../src/components/Hard8JndReference.tsx', import.meta.url), 'utf8');
const hard8OptimizationPanelSource = readFileSync(new URL('../src/components/Hard8JndOptimizationPanel.tsx', import.meta.url), 'utf8');
const cameraProbeSource = readFileSync(new URL('../src/diagnostics/cameraProbe.ts', import.meta.url), 'utf8');
const luminanceEstimatorSource = readFileSync(new URL('../src/diagnostics/luminanceEstimator.ts', import.meta.url), 'utf8');
const i18nIndexSource = readFileSync(new URL('../src/i18n/index.ts', import.meta.url), 'utf8');
const i18nMessagesSource = readFileSync(new URL('../src/i18n/messages.ts', import.meta.url), 'utf8');
const i18nLocalesSource = readFileSync(new URL('../src/i18n/locales.ts', import.meta.url), 'utf8');
const designSource = readFileSync(new URL('../DESIGN.md', import.meta.url), 'utf8');
const designZhTwSource = readFileSync(new URL('../DESIGN.zh-tw.md', import.meta.url), 'utf8');

test('control panel exposes one ordered Signal Path Console workflow', () => {
  assert.match(panelSource, /const SIGNAL_STAGE_COPY/);
  assert.match(panelSource, /function SignalStage/);
  assert.match(panelSource, /const renderSignalPipeline = \(\) =>/);
  assert.match(panelSource, /<SignalStage index="01" title=\{signalCopy\.detail\}/);
  assert.match(panelSource, /<SignalStage index="02" title=\{signalCopy\.transfer\}/);
  assert.match(panelSource, /<SignalStage index="03" title=\{signalCopy\.levels\}/);
  assert.match(panelSource, /<SignalStage index="D" title=\{signalCopy\.diagnostic\}/);
  assert.match(panelSource, /<SignalStage index="04" title=\{signalCopy\.color\}/);
  assert.match(panelSource, /<SignalStage index="05" title=\{signalCopy\.dither\}/);
  assert.match(panelSource, /<Hard8JndOptimizationPanel settings=\{settings\} setSettings=\{setSettings\} messages=\{messages\} \/>/);
  assert.match(panelSource, /function PanelUtilityMenu/);
  assert.match(panelSource, /messages\.panel\.panelUtilities/);
  assert.match(panelSource, /gsdf-levels-command-bar/);
  assert.match(panelSource, /gsdf-header-view-launcher/);
  assert.match(panelSource, /renderSignalPipeline\(\)/);
  assert.match(panelSource, />LumaLift<\/div>/);
  assert.match(panelSource, /GSDF EOTF Adjuster · \{messages\.panel\.subtitle\}/);

  assert.doesNotMatch(panelSource, /PanelTab|activeTab|renderBasicPanel|renderAdvancedPanel/);

  assert.doesNotMatch(panelSource, /PanelLayoutMode/);
  assert.doesNotMatch(panelSource, /PanelLayoutModeSwitch/);
  assert.doesNotMatch(panelSource, /CenterWorkspaceMode/);
  assert.doesNotMatch(panelSource, /panelMode/);
  assert.doesNotMatch(panelSource, /centerMode/);
  assert.doesNotMatch(panelSource, /GSDF_PANEL_MODE_CHANGED/);
  assert.doesNotMatch(panelSource, /layoutModeA|layoutModeB|layoutModeC/);
  assert.doesNotMatch(panelSource, /DiagnosticCameraProbe|GSDF_TARGET_PICK_REQUEST|MousePointer2|renderTargetPickResult/);
});

test('live curve and hard 8-bit JND reference share one pinned reference strip', () => {
  assert.match(panelSource, /type SidePanelMode = 'pattern' \| 'linearity' \| 'bidirectional' \| 'chart'/);
  assert.match(panelSource, /type PinnedReferenceMode = 'curve' \| 'jnd'/);
  assert.match(panelSource, /useState<PinnedReferenceMode>\('curve'\)/);
  assert.match(panelSource, /const renderPinnedReference = \(\) =>/);
  assert.match(panelSource, /className="gsdf-pinned-reference"/);
  assert.match(panelSource, /className="gsdf-pinned-reference__switch"/);
  assert.match(panelSource, /messages\.panel\.pinnedReference/);
  assert.match(panelSource, /setPinnedReferenceMode\('curve'\)/);
  assert.match(panelSource, /setPinnedReferenceMode\('jnd'\)/);
  assert.match(panelSource, /pinnedReferenceMode === 'curve'/);
  assert.match(panelSource, /renderCurvePanel\('gsdf-pinned-reference__curve'/);
  assert.match(panelSource, /<Hard8JndReference settings=\{settings\} messages=\{messages\} \/>/);
  assert.match(panelSource, /className="gsdf-fixed-console"[\s\S]*className="gsdf-panel-header[\s\S]*\{renderPinnedReference\(\)\}/);
  assert.match(panelSource, /className="gsdf-fixed-console"[\s\S]*\{renderPinnedReference\(\)\}[\s\S]*className="gsdf-primary-pane/);
  assert.match(panelSource, /className="gsdf-header-console-row"[\s\S]*gsdf-power-cluster[\s\S]*gsdf-header-view-launcher[\s\S]*gsdf-status-reset/);
  assert.match(panelSource, /gsdf-header-view-launcher[\s\S]*openInspectionWindow\('pattern'\)[\s\S]*openInspectionWindow\('linearity'\)[\s\S]*openInspectionWindow\('bidirectional'\)/);
  assert.match(panelSource, /const openInspectionWindow = [\s\S]*localStorage\.setItem\('gsdf_extension_settings', JSON\.stringify\(settings\)\)[\s\S]*searchParams\.set\('mode', 'inspection'\)[\s\S]*window\.open\([\s\S]*popup=yes/);
  assert.match(appSource, /const isInspectionWindow = searchParams\.get\('mode'\) === 'inspection'/);
  assert.match(appSource, /initialInspectionMode=\{initialInspectionMode\}/);
  assert.match(appSource, /inspectionWindow=\{isInspectionWindow\}/);
  assert.match(appSource, /window\.addEventListener\('storage', handleStorage\)/);
  assert.match(appSource, /event\.key !== 'gsdf_extension_settings'/);
  assert.match(panelSource, /className="h-full min-h-0"/);
  assert.doesNotMatch(panelSource, /className="h-\[150px\]"/);
  assert.match(panelSource, /className="gsdf-signal-scroll min-h-0 flex-1 overflow-y-auto overflow-x-hidden"/);
  assert.match(panelSource, /data-surface-mode=\{sidebarMode \? 'sidebar'/);
  assert.match(panelSource, /!sidebarMode && \(\s*<button[\s\S]*messages\.panel\.closePanel/);
  assert.doesNotMatch(panelSource, /sidePanelOpen|sidePanelRatio|setSidePanelOpen|setSidePanelMode/);
  assert.doesNotMatch(panelSource, /PanelRightOpen/);
  assert.doesNotMatch(panelSource, /className="gsdf-side-panel-divider"/);
  assert.doesNotMatch(panelSource, /PANEL_SIDE_PANEL_WIDTH/);
  assert.match(panelSource, /FullDiagnosticPattern settings=\{settings\} messages=\{messages\}/);
  assert.match(panelSource, /ColorLinearityPattern settings=\{settings\} messages=\{messages\} figureControls=\{figureControls\}/);
  assert.match(panelSource, /CsdfFigureControlsPanel/);
  assert.match(panelSource, /messages\.panel\.fig9Controls/);
  assert.match(panelSource, /ColorBidirectionalPattern settings=\{settings\} messages=\{messages\} renderSize=\{referenceSize\}/);
  assert.match(panelSource, /messages\.panel\.colorLinearityPanel/);
  assert.match(panelSource, /messages\.panel\.bidirectionalColorPanel/);
  assert.match(panelSource, /<GSDFChart[\s\S]*settings=\{settings\}[\s\S]*panelTheme=\{panelTheme\}/);
  assert.match(panelSource, /function ReferenceModeSwitch/);
  assert.match(panelSource, /GSDF_PATTERN_VIEW_CHANGED/);
  assert.match(panelSource, /useExpandedOverlayViewport\(inspectionMode !== null\)/);
  assert.match(panelSource, /PANEL_DEFAULT_WIDTH = 420/);
  assert.match(panelSource, /PANEL_DEFAULT_HEIGHT = 780/);
  assert.match(panelSource, /window\.addEventListener\('resize', syncStandalonePanelSize\)/);
  assert.match(panelSource, /window\.removeEventListener\('resize', syncStandalonePanelSize\)/);
  assert.match(panelSource, /PANEL_MIN_HEIGHT = 560/);
  assert.match(panelSource, /PANEL_MIN_WIDTH = 420/);
  assert.doesNotMatch(panelSource, /legacy-linearity|legacy-rgb|legacyColorLinearity|Legacy RGB/);
});

test('panel keeps project-owned GSDF pattern and chart logic', () => {
  const colorReferenceBlock = panelSource.slice(
    panelSource.indexOf('function getTriangleWave'),
    panelSource.indexOf('function InspectionModeHeader'),
  );
  const bidirectionalBlock = panelSource.slice(
    panelSource.indexOf('function drawBidirectionalColorPattern'),
    panelSource.indexOf('function ColorLinearityPattern'),
  );
  const colorLinearityPatternBlock = panelSource.slice(
    panelSource.indexOf('function drawColorLinearityPattern'),
    panelSource.indexOf('function getReferenceModeOptions'),
  );

  assert.match(panelSource, /drawDiagnosticPattern/);
  assert.match(panelSource, /drawLinePairBand/);
  assert.match(panelSource, /drawVerticalGradient/);
  assert.match(panelSource, /drawContinuousSweepCell/);
  assert.match(panelSource, /drawColorLinearityPattern/);
  assert.match(panelSource, /drawBidirectionalColorPattern/);
  assert.match(panelSource, /function interpolateColor/);
  assert.match(panelSource, /type CsdfFigureMode = 'split' \| 'plain'/);
  assert.match(panelSource, /CSDF_FIG9_DEFAULT_CYCLES = 78/);
  assert.match(panelSource, /CSDF_FIG9_DEFAULT_EXAGGERATION = 1/);
  assert.match(typesSource, /dither: boolean/);
  assert.match(typesSource, /ditherStrength: number/);
  assert.match(typesSource, /ditherColor: boolean/);
  assert.match(typesSource, /ditherNoise: boolean/);
  assert.match(typesSource, /dither: false/);
  assert.match(typesSource, /ditherStrength: DEFAULT_DITHER_STRENGTH/);
  assert.match(typesSource, /ditherNoise: true/);
  assert.match(typesSource, /dither: settings\.dither === true/);
  assert.match(typesSource, /ditherStrength: Math\.round\(clampNumber\(settings\.ditherStrength/);
  assert.match(panelSource, /DITHER_STRENGTH_MIN/);
  assert.match(panelSource, /DITHER_STRENGTH_MAX/);
  assert.match(panelSource, /function applyReferenceOrderedDither/);
  assert.match(panelSource, /getReferenceNoiseDitherOffset\(x, y, 17, strength\)/);
  assert.match(panelSource, /context\.getImageData\(0, 0, imageWidth, imageHeight\)/);
  assert.match(panelSource, /context\.putImageData\(imageData, 0, 0\)/);
  assert.doesNotMatch(chartSource, /ditherChecked|onDitherChange|messages\.chart\.ditherBeta|gsdf-chart-dither-check/);
  assert.match(panelSource, /function ReferenceDitherToggle/);
  assert.match(panelSource, /mode === 'bidirectional'[\s\S]*<ReferenceDitherToggle/);
  assert.match(panelSource, /settings=\{settings\}/);
  assert.match(panelSource, /setSettings=\{setSettings\}/);
  assert.match(panelSource, /settings\.ditherStrength/);
  assert.match(panelSource, /settings\.ditherColor/);
  assert.match(panelSource, /settings\.ditherNoise/);
  assert.match(panelSource, /messages\.panel\.referenceDitherTitle/);
  assert.match(i18nMessagesSource, /referenceDitherStrength: 'Strength'/);
  assert.match(i18nMessagesSource, /referenceDitherColor: 'Use color'/);
  assert.match(i18nMessagesSource, /referenceDitherNoise: 'Use noise'/);
  assert.match(i18nMessagesSource, /ditherBeta: 'Dither Beta'/);
  assert.match(i18nMessagesSource, /Beta noise-dither pass/);
  assert.match(i18nLocalesSource, /ditherBeta: 'Dither Beta'/);
  assert.match(panelSource, /function detectDisplayEnvironment/);
  assert.match(panelSource, /interface ReferenceDisplayScaleStatus/);
  assert.match(panelSource, /function detectReferenceDisplayScaleStatus/);
  assert.match(panelSource, /function useReferenceDisplayScaleStatus/);
  assert.match(panelSource, /function ReferenceDisplayScaleWarning/);
  assert.match(panelSource, /gsdf-display-scale-warning/);
  assert.match(panelSource, /gsdf-display-scale-warning__title/);
  assert.match(panelSource, /gsdf-display-scale-warning__body/);
  assert.match(panelSource, /gsdf-display-scale-warning__metrics/);
  assert.match(panelSource, /gsdf-display-scale-warning__close/);
  assert.match(panelSource, /backgroundColor: '#fff7ed'/);
  assert.match(panelSource, /color: '#431407'/);
  assert.match(panelSource, /color: '#7c2d12'/);
  assert.match(panelSource, /color: '#9a3412'/);
  assert.match(panelSource, /window\.visualViewport\?\.scale/);
  assert.match(panelSource, /hasScaleWarning: hasDeviceScale \|\| hasViewportScale/);
  assert.match(panelSource, /displayScaleStatus\.hasScaleWarning/);
  assert.match(panelSource, /matches\('\(dynamic-range: high\)'\)/);
  assert.match(panelSource, /matches\('\(color-gamut: p3\)'\)/);
  assert.match(panelSource, /window\.screen\?\.colorDepth/);
  assert.match(panelSource, /window\.devicePixelRatio/);
  assert.match(i18nMessagesSource, /displayScaleWarningTitle: 'Display scaling warning'/);
  assert.match(i18nMessagesSource, /dismissDisplayScaleWarning: 'Dismiss display scaling warning'/);
  assert.match(i18nLocalesSource, /displayScaleWarningTitle: '顯示縮放提醒'/);
  assert.match(panelSource, /displayScaleWarningDismissed/);
  assert.match(panelSource, /onDismiss=\{\(\) => setDisplayScaleWarningDismissed\(true\)\}/);
  assert.match(panelSource, /function getAutoTunedCsdfFigureControls/);
  assert.match(panelSource, /targetPhysicalPixelsPerCycle/);
  assert.match(panelSource, /settings\.lmax < 120/);
  assert.match(panelSource, /mode: 'split'/);
  assert.match(panelSource, /function getTriangleWave/);
  assert.match(panelSource, /return 1 - Math\.abs\(2 \* normalizedProgress - 1\)/);
  assert.match(panelSource, /function remapCsdfFig9Channel/);
  assert.match(panelSource, /const gamma = 1 \/ \(1 \+ 0\.8 \* normalizedExaggeration\)/);
  assert.match(panelSource, /function applyCsdfFig9SplitChannel/);
  assert.match(panelSource, /controls\.mode !== 'split' \|\| globalX < renderWidth \/ 2/);
  assert.match(panelSource, /function drawCsdfFig9RampSide/);
  assert.match(panelSource, /const topHeight = Math\.round\(height \* 0\.32\)/);
  assert.match(panelSource, /const middleHeight = Math\.round\(height \* 0\.36\)/);
  assert.match(panelSource, /function applyReferenceGsdfYcbcrToneTable/);
  assert.match(panelSource, /function applyReferenceGsdfRgbToneTable/);
  assert.match(panelSource, /settings\.transferFormula/);
  assert.match(panelSource, /settings\.gsdfPipeline/);
  assert.match(panelSource, /function ChoiceStepperControl/);
  assert.match(chartSource, /const optimizedCurveLabel = settings\.transferFormula === 'csdf'/);
  assert.match(chartSource, /messages\.chart\.csdfOptimized/);
  assert.match(chartSource, /messages\.chart\.gsdfOptimized/);
  assert.match(chartSource, /name=\{optimizedCurveLabel\}/);
  assert.match(i18nMessagesSource, /csdfOptimized: 'CSDF remap'/);
  assert.match(i18nLocalesSource, /csdfOptimized: 'CSDF 重映射'/);
  assert.match(hard8ReferenceSource, /buildHard8JndOptimizationModel/);
  assert.match(hard8ReferenceSource, /current\.nonzeroJndStepSd/);
  assert.match(hard8ReferenceSource, /optimized\.allJndStepSd/);
  assert.match(hard8ReferenceSource, /hard8ReferenceChartAria/);
  assert.match(i18nMessagesSource, /hard8ReferenceTitle: 'Hard 8-bit JND reference'/);
  assert.match(i18nLocalesSource, /hard8ReferenceTitle: '硬 8-bit JND 參考'/);
  assert.match(panelSource, /gsdfPipeline: value === 'gsdf' && prev\.transferFormula !== 'gsdf'[\s\S]*DEFAULT_APP_SETTINGS\.gsdfPipeline/);
  assert.match(i18nMessagesSource, /gsdfPipelineTitle: 'GSDF pipeline'/);
  assert.match(panelSource, /buildLumaChromaMatrices/);
  assert.match(panelSource, /function applyReferenceColorMatrix/);
  assert.match(panelSource, /settings\.displayGamut/);
  assert.match(panelSource, /const ycbcr = applyReferenceColorMatrix\(rgbToUnitColor\(color\), matrices\.forward\)/);
  assert.match(panelSource, /function sampleReferenceToneTable/);
  assert.match(panelSource, /const mappedY = sampleReferenceToneTable\(transferTable, ycbcr\[0\]\)/);
  assert.match(panelSource, /const adjustedRgb = applyReferenceColorMatrix\(\[mappedY, ycbcr\[1\], ycbcr\[2\]\], matrices\.inverse\)/);
  assert.match(panelSource, /function formatColorReferenceRgb/);
  assert.match(panelSource, /function applyActiveReferenceToneTable/);
  assert.match(panelSource, /transferFormula === 'csdf'[\s\S]*return applyReferenceGsdfRgbToneTable\(color, transferTable\)/);
  assert.match(panelSource, /context\.fillStyle = formatRgb\(topBottomColor\)/);
  assert.match(panelSource, /context\.fillStyle = formatRgb\(middleColor\)/);
  assert.match(panelSource, /context\.fillStyle = formatColorReferenceRgb\(row\.base, transferTable, settings\)/);
  assert.doesNotMatch(colorLinearityPatternBlock, /const transferTable = buildGsdfTableValues\(settings\)/);
  assert.match(colorLinearityPatternBlock, /const transferTable = buildActiveTransferTableValues\(settings\)/);
  assert.match(colorLinearityPatternBlock, /transferTable,[\s\S]*settings/);
  assert.match(colorLinearityPatternBlock, /applyReferenceOrderedDither\(context, renderWidth, renderHeight, settings\)/);
  assert.match(panelSource, /function applyColorReferenceToneTableFloat/);
  assert.match(bidirectionalBlock, /context\.canvas\.width/);
  assert.match(bidirectionalBlock, /context\.setTransform\(1, 0, 0, 1, 0, 0\)/);
  assert.match(bidirectionalBlock, /applyColorReferenceToneTableFloat\(/);
  assert.match(bidirectionalBlock, /transferTable,\s*settings/);
  assert.match(panelSource, /drawBidirectionalColorPattern\(context, settings, size\.width, size\.height\)/);
  assert.match(panelSource, /applyReferenceOrderedDither\(context, renderWidth, renderHeight, settings\)/);
  assert.match(bidirectionalBlock, /applyReferenceOrderedDither\(context, pixelWidth, pixelHeight, settings\)/);
  assert.doesNotMatch(contentSource, /ditherPreview|applyReferenceOrderedDither|REFERENCE_ORDERED_DITHER_MATRIX/);
  assert.match(contentSource, /gsdf-eotf-dither/);
  assert.match(contentSource, /feTurbulence/);
  assert.match(contentSource, /-noise-mix/);
  assert.match(contentSource, /-color-mix/);
  assert.match(contentSource, /profile\.ditherFilterId \? formatFilterUrl\(profile\.ditherFilterId\) : ''/);
  assert.doesNotMatch(panelSource, /const rampRatio = inverted \? 1 - baseRatio : baseRatio/);
  assert.match(panelSource, /CMY_RGB_GRADIENT_STOPS/);
  assert.match(panelSource, /function drawCmyRgbContinuousGradientBand/);
  assert.match(panelSource, /function sampleCmyRgbGradient/);
  assert.match(bidirectionalBlock, /drawCmyRgbContinuousGradientBand\(context, 0, 0, pixelWidth, pixelHeight, transferTable, settings\)/);
  assert.doesNotMatch(bidirectionalBlock, /bandGap|topHeight|bottomHeight|reversed/);
  assert.doesNotMatch(panelSource, /function drawSingleDirectionColorRamp/);
  assert.doesNotMatch(panelSource, /function drawBidirectionalColorBand/);
  assert.doesNotMatch(panelSource, /function selectDiscreteGradientLineColor/);
  assert.doesNotMatch(panelSource, /BIDIRECTIONAL_COLOR_SAMPLE_COUNT/);
  assert.doesNotMatch(panelSource, /COLOR_LINE_PERIOD/);
  assert.doesNotMatch(panelSource, /drawDiscreteGradientSample/);
  assert.doesNotMatch(colorReferenceBlock, /context\.strokeRect/);
  assert.doesNotMatch(colorReferenceBlock, /strokeStyle = 'rgba\(0,0,0/);
  assert.doesNotMatch(panelSource, /context\.fillRect\(marginX, y \+ rowHeight \/ 2 - 1, patternWidth, 2\)/);
  assert.doesNotMatch(colorReferenceBlock, /calibratedSimulation/);
  assert.doesNotMatch(bidirectionalBlock, /sampleIndex/);
  assert.match(panelSource, /COLOR_LINEARITY_ROWS/);
  assert.match(panelSource, /amplitudePercent: 3\.0/);
  assert.match(panelSource, /differencePercent: 5\.9/);
  assert.match(panelSource, /COLOR_LINEARITY_PATTERN_HEIGHT = 920/);
  assert.match(panelSource, /function getScreenAwareReferenceSize/);
  assert.match(panelSource, /function fitDiagnosticPatternSizeToViewport/);
  assert.match(panelSource, /DIAGNOSTIC_PATTERN_MIN_VIEWPORT_ASPECT/);
  assert.match(panelSource, /DIAGNOSTIC_PATTERN_MIN_VIEWPORT_ASPECT = 3 \/ 4/);
  assert.match(panelSource, /mode === 'pattern'[\s\S]*fitDiagnosticPatternSizeToViewport\(availableSize\)/);
  assert.match(panelSource, /function useReferenceCanvas/);
  assert.match(panelSource, /getMeasuredReferenceCanvasSize\(canvas\)/);
  assert.match(panelSource, /renderSize \?\? getMeasuredReferenceCanvasSize\(canvas\)/);
  assert.match(panelSource, /drawPaperComparisonRamp/);
  assert.match(panelSource, /drawCsdfFig9LogoBlock/);
  assert.doesNotMatch(panelSource, /drawLegacyColorLinearityLogoBlock/);
  assert.match(panelSource, /BIDIRECTIONAL_COLOR_PATTERN_WIDTH = 1800/);
  assert.match(panelSource, /DIAGNOSTIC_PATTERN_WIDTH = 2048/);
  assert.match(panelSource, /const observationWidth = 520/);
  assert.match(panelSource, /const chartW = 1540/);
  assert.match(panelSource, /viewportScaleInfo/);
  assert.match(panelSource, /viewportScaleBest/);
  assert.match(panelSource, /bg-emerald-300 px-2 py-1 text-\[12px\] font-black text-black/);
  assert.match(panelSource, /fixedDesignSize/);
  assert.match(panelSource, /drawScaledReferenceDesign/);
  assert.match(panelSource, /useScreenAwareReferenceSize\(mode\)/);
  assert.match(panelSource, /getAutoTunedCsdfFigureControls\(settings, renderSize\)/);
  assert.match(i18nMessagesSource, /resetFig9Controls: 'Auto-tune CSDF reference side-view controls from the current display environment'/);
  assert.doesNotMatch(panelSource, /column % 22 === 0 \? '#ffffff' : '#000000'/);
  assert.match(i18nMessagesSource, /CSDF VISUAL TEST PATTERN/);
  assert.match(diagnosticProbeSource, /requestCameraStream/);
  assert.match(diagnosticProbeSource, /createCameraCapabilitySnapshot/);
  assert.match(diagnosticProbeSource, /analyzeLuminanceFrame/);
  assert.match(diagnosticProbeSource, /estimateLuminance/);
  assert.match(diagnosticProbeSource, /roughMeterBoundary/);
  assert.match(cameraProbeSource, /getUserMedia/);
  assert.match(cameraProbeSource, /getCapabilities/);
  assert.match(cameraProbeSource, /getPhotoCapabilities/);
  assert.match(luminanceEstimatorSource, /srgbToLinear/);
  assert.match(luminanceEstimatorSource, /clipHighRatio/);
  assert.match(luminanceEstimatorSource, /stabilityScore/);
  assert.match(panelSource, /getRecommendedImageDefaults\(prev\.lmax\)/);
  assert.match(panelSource, /getRecommendedImageDefaults\(nextLmax\)/);
  assert.match(typesSource, /const transferTable = buildActiveTransferTableValues\(normalized\)/);
  assert.match(typesSource, /sampleTableValue\(transferTable, baseRatio\)/);
  assert.match(typesSource, /gammaCorrectionToTarget/);
  assert.match(typesSource, /gammaTargetToCorrection/);
  assert.match(panelSource, /React\.lazy/);
  assert.match(panelSource, /React\.Suspense/);
  assert.match(panelSource, /import\('\.\/GSDFChart'\)/);
});

test('the JND diagnostic branch owns its route-matched optimization action', () => {
  const optimizeBlock = panelSource.slice(
    panelSource.indexOf('const applyOptimizedLevels = () =>'),
    panelSource.indexOf('const setLmaxWithLinkedDefaults ='),
  );

  assert.match(panelSource, /DEFAULT_TARGET_LUMINANCE_NITS/);
  assert.match(panelSource, /LUMINANCE_REFERENCE_MARKS = \[58, DEFAULT_TARGET_LUMINANCE_NITS, 160, 203, 300\]/);
  assert.match(panelSource, /GAMMA_NEUTRAL_SLIDER_VALUE = luminanceToSliderValue\(DEFAULT_TARGET_LUMINANCE_NITS\)/);
  assert.match(panelSource, /SPECIAL_MARK_SNAP_THRESHOLD = 8/);
  assert.match(panelSource, /function snapSliderValueToMarks/);
  assert.match(panelSource, /function gammaCorrectionToAlignedSliderValue/);
  assert.match(panelSource, /function alignedSliderValueToGammaCorrection/);
  assert.match(panelSource, /function gammaTargetToAlignedSliderValue/);
  assert.match(optimizeBlock, /buildHard8JndOptimizationModel\(settings, settings\.hard8JndLevelCount\)/);
  assert.match(optimizeBlock, /hard8JndOptimizationEnabled: true/);
  assert.match(optimizeBlock, /hard8JndLevelCount: model\.recommendedLevelCount/);
  assert.doesNotMatch(optimizeBlock, /setActiveTab/);
  assert.doesNotMatch(optimizeBlock, /lmax: 100|gammaTarget: DEFAULT_APP_SETTINGS|transferFormula: DEFAULT_APP_SETTINGS/);
  assert.match(hard8OptimizationPanelSource, /hard8JndOptimizationEnabled: true/);
  assert.match(hard8OptimizationPanelSource, /hard8JndOptimizationEnabled: false/);
  assert.match(hard8OptimizationPanelSource, /hard8OptimizationApply/);
  assert.match(panelSource, /<SignalStage index="D"[\s\S]*branch>/);
  assert.match(panelSource, /<details className="gsdf-signal-diagnostic">/);
  assert.match(panelSource, /<div className="gsdf-levels-command-bar">[\s\S]*onClick=\{applyOptimizedLevels\}/);
  assert.doesNotMatch(panelSource, /gsdf-header-action-stack/);
  assert.match(i18nMessagesSource, /optimizePreset: 'Optimize levels'/);
  assert.match(i18nLocalesSource, /optimizePreset: '最佳階數'/);
});

test('ordered signal stages expose every correction control', () => {
  const curvePanelBlock = panelSource.slice(
    panelSource.indexOf('const renderCurvePanel ='),
    panelSource.indexOf('const renderSignalPipeline = () =>'),
  );
  const pipelineBlock = panelSource.slice(
    panelSource.indexOf('const renderSignalPipeline = () =>'),
    panelSource.indexOf('const handleHeaderPointerDown'),
  );
  const headerConsoleBlock = panelSource.slice(
    panelSource.indexOf('<div className="gsdf-header-console-row"'),
    panelSource.indexOf('{renderPinnedReference()}'),
  );

  assert.match(panelSource, /function CheckboxControl/);
  assert.match(panelSource, /function CompactAdjustControl/);
  assert.match(panelSource, /function normalizeSteppedValue/);
  assert.match(panelSource, /BUTTON_AUTO_REPEAT_DELAY_MS = 1500/);
  assert.match(panelSource, /BUTTON_AUTO_REPEAT_INTERVAL_MS = 120/);
  assert.match(panelSource, /function useAutoRepeatButton/);
  assert.match(panelSource, /window\.setTimeout\(\(\) => \{[\s\S]*BUTTON_AUTO_REPEAT_DELAY_MS/);
  assert.match(panelSource, /window\.setInterval\(\(\) => \{[\s\S]*BUTTON_AUTO_REPEAT_INTERVAL_MS/);
  assert.match(panelSource, /const decreaseHandlers = useAutoRepeatButton/);
  assert.match(panelSource, /const increaseHandlers = useAutoRepeatButton/);
  assert.match(pipelineBlock, /messages\.panel\.displayGamma/);
  assert.match(pipelineBlock, /messages\.panel\.displayGammaInverseHint/);
  assert.match(pipelineBlock, /messages\.panel\.displayGammaTitle/);
  assert.match(pipelineBlock, /DisplayGammaSelect/);
  assert.match(pipelineBlock, /gammaScaleMarks/);
  assert.match(pipelineBlock, /GAMMA_REFERENCE_MARKS/);
  assert.match(pipelineBlock, /gammaTargetToAlignedSliderValue\(option, settings\.displayGamma\)/);
  assert.match(pipelineBlock, /marks=\{gammaScaleMarks\}/);
  assert.match(pipelineBlock, /snapValues=\{gammaSnapValues\}/);
  assert.match(panelSource, /LUMINANCE_REFERENCE_MARKS\.map/);
  assert.match(panelSource, /luminanceToSliderValue\(mark\)/);
  assert.match(panelSource, /luminanceSnapValues/);
  assert.match(pipelineBlock, /snapValues=\{luminanceSnapValues\}/);
  assert.match(curvePanelBlock, /messages\.panel\.curvePanel/);
  assert.match(curvePanelBlock, /title = messages\.panel\.curvePanel/);
  assert.match(curvePanelBlock, /GSDFChart/);
  assert.match(curvePanelBlock, /toolbarLeading/);
  assert.match(curvePanelBlock, /toolbarAction/);
  assert.match(curvePanelBlock, /gsdf-chart-frame/);
  assert.match(pipelineBlock, /label=\{messages\.panel\.lmaxLabel\}[\s\S]*snapValues=\{luminanceSnapValues\}/);
  assert.doesNotMatch(pipelineBlock, /renderCurvePanel\('gsdf-signal-curve-dock'/);
  assert.match(pipelineBlock, /gammaCorrectionToAlignedSliderValue\(gammaCorrection\)/);
  assert.match(pipelineBlock, /setGammaCorrection\(alignedSliderValueToGammaCorrection\(value\)\)/);
  assert.match(pipelineBlock, /setDisplayGamma\(value\)/);
  assert.match(pipelineBlock, /setNumericSetting\('gammaTarget', settings\.displayGamma\)/);
  assert.match(pipelineBlock, /rangeRowClassName="gsdf-gamma-range-row"/);
  assert.match(pipelineBlock, /calibratedRange/);
  assert.match(pipelineBlock, /gsdf-gamma-control/);
  assert.match(pipelineBlock, /gsdf-filter-stepper-control/);
  assert.match(pipelineBlock, /metaText=\{`\$\{settings\.transferFormula\.toUpperCase\(\)\} mix`\}/);
  assert.match(pipelineBlock, /className="gsdf-filter-scope"/);
  assert.match(pipelineBlock, /className="gsdf-filter-scope__effects"[\s\S]*messages\.panel\.lmaxLabel[\s\S]*messages\.panel\.routeFormula[\s\S]*messages\.panel\.gsdfPipelineTitle[\s\S]*messages\.panel\.displayGamut[\s\S]*className="gsdf-filter-scope__mix"/);
  assert.match(pipelineBlock, /className="gsdf-filter-scope__junction"/);
  assert.match(pipelineBlock, /className="gsdf-filter-scope__mix"[\s\S]*messages\.panel\.filterLabel/);
  assert.doesNotMatch(panelSource, /function StatusModeStrip|gsdf-header-status-strip/);
  assert.doesNotMatch(headerConsoleBlock, /messages\.panel\.correctionRoute|gsdf-status-caption/);
  assert.match(headerConsoleBlock, /aria-pressed=\{settings\.enabled\}/);
  assert.match(headerConsoleBlock, /gsdf-header-view-launcher/);
  assert.match(headerConsoleBlock, /openInspectionWindow\('pattern'\)/);
  assert.match(headerConsoleBlock, /openInspectionWindow\('linearity'\)/);
  assert.match(headerConsoleBlock, /openInspectionWindow\('bidirectional'\)/);
  assert.doesNotMatch(headerConsoleBlock, /openInspectionMode\(/);
  assert.doesNotMatch(headerConsoleBlock, /gsdf-signal-route-summary|flowSummary/);
  assert.match(panelSource, /data-state=\{settings\.enabled \? 'on' : 'off'\}/);
  assert.doesNotMatch(panelSource, /onResetDefault/);
  assert.match(panelSource, /gsdf-header-console-row/);
  assert.doesNotMatch(panelSource, /gsdf-header-active-row|gsdf-header-navigation-row/);
  assert.match(panelSource, /PanelUtilityMenu/);
  assert.match(panelSource, /function ChoiceStepperControl/);
  assert.match(pipelineBlock, /<ChoiceStepperControl[\s\S]*label=\{messages\.panel\.routeFormula\}/);
  assert.match(pipelineBlock, /<ChoiceStepperControl[\s\S]*label=\{messages\.panel\.gsdfPipelineTitle\}/);
  assert.match(pipelineBlock, /<ChoiceStepperControl[\s\S]*label=\{messages\.panel\.displayGamut\}/);
  assert.match(pipelineBlock, /onChange=\{setTransferFormula\}/);
  assert.match(pipelineBlock, /disabled=\{settings\.transferFormula !== 'gsdf'\}/);
  assert.doesNotMatch(panelSource, /gsdf-status-formula-row/);
  assert.doesNotMatch(panelSource, /gsdf-status-metric-row/);
  assert.doesNotMatch(panelSource, /gsdf-status-inline-metrics/);
  assert.doesNotMatch(panelSource, /<ModePill title=\{messages\.panel\.gammaPillTitle\}/);
  assert.doesNotMatch(panelSource, /<ModePill title=\{messages\.panel\.filterPillTitle\}/);
  assert.match(panelSource, /gsdf-control-leading/);
  assert.match(panelSource, /gsdf-control-value-label/);
  assert.match(panelSource, /function DualLevelAxisControl/);
  assert.match(panelSource, /const remainingToneCount = Math\.max\(0, whiteValue - blackValue\)/);
  assert.match(pipelineBlock, /<DualLevelAxisControl/);
  assert.match(pipelineBlock, /remainingLabel=\{`\$\{signalCopy\.remainingTones\} \/ \$\{TONE_LEVEL_COUNT\}`\}/);
  assert.match(pipelineBlock, /TONE_LEVEL_COUNT/);
  assert.match(panelSource, /BLACK_CLIP_TONE_MAX/);
  assert.match(panelSource, /WHITE_CLIP_TONE_MIN/);
  assert.match(typesSource, /BLACK_CLIP_TONE_MAX = TONE_LEVEL_COUNT - 1/);
  assert.match(typesSource, /WHITE_CLIP_TONE_MIN = 1/);
  assert.match(panelSource, /Math\.min\(BLACK_CLIP_TONE_MAX, whiteValue - 1/);
  assert.match(panelSource, /Math\.max\(WHITE_CLIP_TONE_MIN, blackValue \+ 1/);
  assert.match(pipelineBlock, /messages\.panel\.fineDetailSharpening/);
  assert.match(pipelineBlock, /messages\.panel\.mediumDetailSharpening/);
  assert.match(pipelineBlock, /fineSharpness/);
  assert.match(pipelineBlock, /mediumSharpness/);
  assert.match(pipelineBlock, /TEMPERATURE_MIN_K/);
  assert.match(pipelineBlock, /TEMPERATURE_MAX_K/);
  assert.match(pipelineBlock, /SATURATION_MIN/);
  assert.match(pipelineBlock, /SATURATION_MAX/);
  assert.match(pipelineBlock, /messages\.panel\.grayscale/);
  assert.match(pipelineBlock, /getRecommendedImageDefaults\(settings\.lmax\)\.saturation/);
  assert.match(panelSource, /gsdf-level-axis__track/);
  assert.match(pipelineBlock, /step=\{50\}/);
  assert.match(pipelineBlock, /<SignalStage index="05"[\s\S]*<ReferenceDitherToggle/);
  assert.match(pipelineBlock, /<ReferenceDitherToggle[\s\S]*compact/);
  assert.doesNotMatch(pipelineBlock, /gsdf-signal-dither-link/);
});

test('controls preserve expected interaction and resize affordances', () => {
  assert.match(panelSource, /function isInteractiveDragTarget/);
  assert.match(panelSource, /function isViewportPanBlockedTarget/);
  assert.match(panelSource, /button, input, label, select, textarea, a/);
  assert.match(panelSource, /data-no-drag/);
  assert.match(panelSource, /target instanceof Element/);
  assert.match(panelSource, /data-panel-drag-handle/);
  assert.match(panelSource, /data-viewport-ui/);
  assert.match(panelSource, /function InteractiveInspectionViewport/);
  assert.match(panelSource, /type InspectionScaleMode = 'actual' \| 'cover' \| 'fit'/);
  assert.match(panelSource, /scaleMode: 'actual'/);
  assert.match(panelSource, /getNextInspectionScaleMode/);
  assert.match(panelSource, /INSPECTION_ZOOM_MIN/);
  assert.match(panelSource, /onWheel=\{handleWheel\}/);
  assert.match(panelSource, /onPointerDown=\{handlePointerDown\}/);
  assert.match(panelSource, /onDoubleClick=\{handleDoubleClick\}/);
  assert.match(panelSource, /isViewportPanBlockedTarget\(event\.target\)/);
  assert.match(panelSource, /offsetX: current\.offsetX \+ deltaX/);
  assert.match(panelSource, /getDefaultInspectionSize/);
  assert.match(panelSource, /EffectSwitch/);
  assert.match(panelSource, /role="switch"/);
  assert.match(panelSource, /aria-checked=\{enabled\}/);
  assert.match(panelSource, /PanelBorderResizeHandles/);
  assert.match(panelSource, /data-resize-handle="e"/);
  assert.match(panelSource, /data-resize-handle="s"/);
  assert.match(panelSource, /data-resize-handle="se"/);
  assert.match(panelSource, /getResizeDeltas/);
  assert.match(appSource, /type: 'GSDF_PANEL_RESIZED'/);
  assert.match(appSource, /type: 'GSDF_CLOSE_PANEL'/);
  assert.match(panelSource, /onExtensionResize\?\.\(deltaWidth, deltaHeight\)/);
  assert.match(panelSource, /PANEL_TEXT_SCALE_STORAGE_KEY = 'gsdf_panel_text_scale'/);
  assert.match(panelSource, /function TextScaleControls/);
  assert.match(panelSource, /style=\{scaledPanelStyle\}/);
});

test('visual language keeps the precision-panel styling hooks', () => {
  const cssSource = readFileSync(new URL('../src/index.css', import.meta.url), 'utf8');

  assert.match(cssSource, /\.gsdf-panel-shell/);
  assert.match(cssSource, /--gsdf-ui-text-scale/);
  assert.match(cssSource, /--gsdf-space-1: 4px/);
  assert.match(cssSource, /--gsdf-space-1-5: 6px/);
  assert.match(cssSource, /--gsdf-space-2: 8px/);
  assert.match(cssSource, /--gsdf-space-3: 12px/);
  for (const token of ['--gsdf-space-0-5', '--gsdf-space-1', '--gsdf-space-1-5', '--gsdf-space-2', '--gsdf-space-3']) {
    assert.match(cssSource, new RegExp(`var\\(${token}\\)`));
  }
  assert.doesNotMatch(cssSource, /--gsdf-space-2-5|--gsdf-space-4|--gsdf-space-5|--gsdf-space-6/);
  assert.match(cssSource, /--gsdf-panel-min-width: 420px/);
  assert.match(cssSource, /--gsdf-panel-min-height: 560px/);
  assert.match(cssSource, /\.gsdf-panel-title-row/);
  assert.match(cssSource, /\.gsdf-window-actions/);
  assert.match(cssSource, /\.gsdf-header-toolbar/);
  assert.match(cssSource, /\.gsdf-header-controls/);
  assert.match(cssSource, /\.gsdf-header-active-row/);
  assert.match(cssSource, /grid-template-columns: minmax\(132px, 158px\) minmax\(0, 1fr\) 34px/);
  assert.match(cssSource, /align-items: start/);
  assert.match(cssSource, /\.gsdf-header-navigation-row/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-header-navigation-row \{\s*grid-template-columns: minmax\(0, 1fr\);/);
  assert.match(cssSource, /\.gsdf-utility-menu__popover/);
  assert.match(cssSource, /\.gsdf-levels-command-bar/);
  assert.match(cssSource, /\.gsdf-nav-row \.gsdf-tab-switch/);
  assert.match(cssSource, /\.gsdf-panel-header/);
  assert.match(cssSource, /\[data-panel-drag-handle\]/);
  assert.match(cssSource, /\.gsdf-text-scale-controls/);
  assert.match(cssSource, /\.gsdf-status-mode-strip/);
  assert.match(cssSource, /\.gsdf-status-caption/);
  assert.match(cssSource, /\.gsdf-status-caption-kicker/);
  assert.match(cssSource, /\.gsdf-status-caption-route/);
  assert.match(cssSource, /\.gsdf-route-control-block/);
  assert.match(cssSource, /\.gsdf-route-control-row/);
  assert.match(cssSource, /background: transparent !important/);
  assert.match(cssSource, /@container \(min-width: 700px\)/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-header-active-row \{\s*grid-template-columns: minmax\(0, 1fr\) 34px !important;/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-power-cluster \{\s*gap: 8px;\s*overflow: visible;/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-power-status \{\s*min-width: 108px;/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-status-caption \{\s*min-height: 42px;/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-power-cluster\[aria-pressed="true"\] \{[\s\S]*background: linear-gradient\(90deg, rgba\(25, 50, 33, 0\.78\), rgba\(20, 39, 28, 0\.58\)\) !important/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-numeric-control--slider/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-numeric-control--stepper/);
  assert.doesNotMatch(cssSource, /gsdf-status-formula-row/);
  assert.doesNotMatch(cssSource, /gsdf-status-metric-row/);
  assert.doesNotMatch(cssSource, /gsdf-status-inline-metrics/);
  assert.match(cssSource, /\.gsdf-panel-shell\.theme-light \.gsdf-power-cluster\[aria-pressed="true"\] \{[\s\S]*background: linear-gradient\(90deg, #dcfce7, #f0fdf4\) !important/);
  assert.match(cssSource, /\.gsdf-panel-section-stack/);
  assert.match(cssSource, /\.gsdf-basic-tuning-stack/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-choice-stepper/);
  assert.match(cssSource, /\.gsdf-choice-stepper-value/);
  assert.match(cssSource, /\.gsdf-basic-primary-grid/);
  assert.match(cssSource, /\.gsdf-advanced-grid/);
  assert.match(cssSource, /\.gsdf-advanced-group--tone \.gsdf-tone-pair/);
  assert.match(cssSource, /\.gsdf-compact-adjust-control/);
  assert.match(cssSource, /\.gsdf-compact-stepper/);
  assert.match(cssSource, /min-height: 46px/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-compact-adjust-control/);
  assert.match(cssSource, /\.gsdf-control-block/);
  assert.match(cssSource, /\.gsdf-control-headline/);
  assert.match(cssSource, /\.gsdf-control-reset/);
  assert.match(cssSource, /\.gsdf-range-mark--major/);
  assert.match(cssSource, /\.gsdf-basic-curve-block/);
  assert.match(cssSource, /\.gsdf-filter-stepper-control/);
  assert.match(cssSource, /\.gsdf-filter-scope \{/);
  assert.match(cssSource, /\.gsdf-filter-scope__effects \{/);
  assert.match(cssSource, /\.gsdf-filter-scope__mix \{/);
  assert.match(cssSource, /\.gsdf-filter-scope__junction \{/);
  assert.match(cssSource, /flex-direction: row/);
  assert.match(cssSource, /\.gsdf-chart-toolbar/);
  assert.match(cssSource, /\.gsdf-chart-legend/);
  assert.match(cssSource, /\.gsdf-chart-levels-check::after/);
  assert.match(cssSource, /\.gsdf-chart-levels-check:checked/);
  assert.match(cssSource, /color: rgba\(248, 113, 113, 0\.58\)/);
  assert.match(cssSource, /opacity: 0\.58/);
  assert.match(cssSource, /color: #ff2d2d/);
  assert.match(cssSource, /background:\s*linear-gradient\(180deg, rgba\(255, 255, 255, 0\.98\), rgba\(241, 246, 251, 0\.92\)\) !important/);
  assert.match(cssSource, /background:\s*linear-gradient\(180deg, rgba\(0, 0, 0, 0\.98\), rgba\(7, 10, 14, 0\.98\)\) !important/);
  assert.match(cssSource, /\.gsdf-chart-viewport/);
  assert.match(cssSource, /\.gsdf-tab-switch/);
  assert.match(cssSource, /\.gsdf-checkbox/);
  assert.match(cssSource, /\.gsdf-gamma-control,\s*\.gsdf-filter-control/);
  assert.match(cssSource, /\.gsdf-gamma-control \.gsdf-control-value-label/);
  assert.match(cssSource, /\.gsdf-gamma-control \{\s*display: grid;\s*grid-template-rows: auto minmax\(34px, 1fr\);/);
  assert.match(cssSource, /\.gsdf-gamma-control > \.gsdf-range-with-reset \{\s*align-self: start;/);
  assert.match(cssSource, /\.gsdf-gamma-control \.gsdf-control-headline \{\s*align-self: end;/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-lmax-readout \{\s*margin-top: 5px;/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-gamma-control \.gsdf-control-headline \{\s*margin-right: 32px;\s*margin-bottom: 24px;\s*padding-bottom: 6px;/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-gamma-control \.gsdf-control-trailing \.gsdf-control-value-label \{\s*height: 28px;\s*padding: 2px;\s*line-height: 24px;/);
  assert.match(cssSource, /font-family: ui-monospace, SFMono-Regular, "SF Mono", Menlo, Consolas, monospace !important/);
  assert.match(cssSource, /\.gsdf-control-value-row/);
  assert.match(cssSource, /\.gsdf-gamma-control \.gsdf-control-value-row/);
  assert.match(cssSource, /\.gsdf-gamma-range-row \.gsdf-range/);
  assert.match(cssSource, /\.gsdf-gamma-control \.gsdf-range-with-reset/);
  assert.match(cssSource, /\.gsdf-gamma-control \.gsdf-inline-select/);
  assert.match(cssSource, /background: transparent/);
  assert.match(cssSource, /\.gsdf-calibrated-range-row \.gsdf-range/);
  assert.match(cssSource, /flex: 0 0 calc\(100% \+ 44px\)/);
  assert.match(cssSource, /width: calc\(100% \+ 44px\)/);
  assert.match(cssSource, /padding-block: 18px/);
  assert.match(cssSource, /min-height: 128px/);
  assert.match(cssSource, /\.gsdf-gamma-control \.gsdf-inline-select > span:last-child/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-camera-preview \.text-zinc-300/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-display-scale-warning/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-display-scale-warning__title/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-display-scale-warning__body/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-display-scale-warning__metrics/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-display-scale-warning__close/);
  assert.match(cssSource, /\.gsdf-choice-stepper-control/);
  assert.match(cssSource, /\.gsdf-signal-conditional\[aria-disabled="true"\]/);
  assert.match(cssSource, /border-radius: 3px !important/);
  assert.match(cssSource, /border-radius: 8px !important/);
  assert.match(cssSource, /border-radius: 12px !important/);
  assert.match(cssSource, /\.gsdf-panel-header \.gsdf-icon-button/);
  assert.match(cssSource, /min-width: 36px/);
  assert.match(cssSource, /min-height: 36px/);
  assert.match(cssSource, /\.gsdf-panel-title-row \.gsdf-text-button select/);
  assert.match(cssSource, /height: 36px/);
  assert.match(cssSource, /min-height: 36px/);
  assert.match(cssSource, /width: 50px/);
  assert.match(cssSource, /\.gsdf-header-controls \.gsdf-power-cluster \{\s*min-height: 42px;\s*height: 42px;/);
  assert.match(cssSource, /\.gsdf-header-controls \.gsdf-effect-switch \{\s*position: relative;\s*width: 48px;\s*height: 30px;\s*overflow: hidden;/);
  assert.match(cssSource, /\.gsdf-header-controls \.gsdf-effect-switch > span:last-child \{\s*position: absolute !important;\s*top: 4px;\s*left: 4px;\s*width: 22px;\s*height: 22px;\s*translate: 0 !important;/);
  assert.match(cssSource, /\.gsdf-filter-stepper-control \.gsdf-compact-adjust-actions/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-numeric-control--stepper \.gsdf-compact-adjust-actions/);
  assert.match(cssSource, /grid-template-columns: minmax\(108px, 1fr\) auto/);
  assert.match(cssSource, /\.gsdf-chart-frame/);
  assert.match(cssSource, /padding: 2px !important/);
  assert.match(cssSource, /\.gsdf-panel-shell \.gsdf-chart-toolbar \{\s*margin: 2px 10px 1px 2px;/);
  assert.match(cssSource, /\.gsdf-pinned-reference/);
  assert.match(cssSource, /\.gsdf-pinned-reference__switch/);
  assert.match(cssSource, /\.gsdf-pinned-reference__curve/);
  assert.match(cssSource, /\.gsdf-fixed-console \{[\s\S]*height: clamp\(270px, 44dvh, 388px\)/);
  assert.match(cssSource, /\.gsdf-header-console-row \{[\s\S]*grid-template-columns: minmax\(132px, 154px\) minmax\(0, 1fr\) 34px/);
  assert.match(cssSource, /\.gsdf-header-view-launcher \{[\s\S]*grid-template-columns: repeat\(3, minmax\(0, 1fr\)\)/);
  assert.match(cssSource, /\.gsdf-header-view-button \{[\s\S]*min-height: 36px/);
  assert.match(cssSource, /\.gsdf-fixed-console \.gsdf-pinned-reference__body \{[\s\S]*flex: 1 1 auto/);
  assert.match(cssSource, /\.gsdf-fixed-console \.gsdf-pinned-reference__curve \.gsdf-chart-frame \{[\s\S]*height: auto;[\s\S]*flex: 1 1 auto/);
  assert.match(cssSource, /\.gsdf-fixed-console \.gsdf-hard8-reference__metrics \{[\s\S]*grid-template-columns: repeat\(4, minmax\(0, 1fr\)\)/);
  assert.match(cssSource, /@media \(max-height: 620px\) \{[\s\S]*height: clamp\(292px, 48dvh, 310px\)/);
  assert.match(cssSource, /\.gsdf-signal-scroll/);
  assert.match(cssSource, /\.gsdf-terminal-dither-control/);
  assert.match(cssSource, /data-surface-mode="sidebar"/);
  assert.match(cssSource, /\.gsdf-reference-panel/);
  assert.match(cssSource, /\.gsdf-hard8-reference__chart/);
  assert.match(cssSource, /\.gsdf-hard8-reference__line--optimized/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-hard8-reference/);
  assert.match(cssSource, /\.gsdf-jnd-workbench__level-control/);
  assert.match(cssSource, /\.gsdf-jnd-workbench__chart--jnd/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-primary-pane/);
  assert.match(cssSource, /\.gsdf-panel\.theme-light \.gsdf-jnd-workbench/);
  assert.match(cssSource, /\.gsdf-diagnostic-placeholder/);
  assert.match(cssSource, /\.gsdf-camera-probe/);
  assert.match(cssSource, /\.gsdf-camera-preview/);
  assert.match(cssSource, /\.gsdf-range::-webkit-slider-thumb \{\s*width: 12px;\s*height: 18px;/);
  assert.match(cssSource, /touch-action: manipulation/);
  assert.match(cssSource, /touch-action: none/);
  assert.doesNotMatch(cssSource, /gsdf-floating-window/);
});

test('content panel drag is frame-throttled and keeps tab-bound iframe control', () => {
  assert.match(contentSource, /function schedulePanelDrag/);
  assert.match(contentSource, /pendingPanelDrag/);
  assert.match(contentSource, /scheduleAnimationFrame/);
  assert.match(contentSource, /uiIframe\.style\.left = `\$\{panelPosition\.x\}px`/);
  assert.match(contentSource, /uiIframe\.style\.top = `\$\{panelPosition\.y\}px`/);
  assert.match(contentSource, /willChange: 'left, top, width, height'/);
  assert.match(contentSource, /uiIframe\.src = chrome\.runtime\.getURL\('ui\/index\.html\?mode=extension'\)/);
  assert.doesNotMatch(contentSource, /translate3d/);
  assert.doesNotMatch(contentSource, /chrome\.windows\.create/);
});

test('native side panel keeps settings synchronized with the active managed tab', () => {
  assert.match(appSource, /searchParams\.get\('mode'\) === 'sidepanel'/);
  assert.match(appSource, /chromeApi\.tabs\?\.query\(\{ active: true, currentWindow: true \}/);
  assert.match(appSource, /action: 'apply_settings'/);
  assert.match(appSource, /onActivated\?\.addListener/);
  assert.match(appSource, /changeInfo\.status === 'complete'/);
  assert.match(appSource, /sidebarMode=\{isSidePanel\}/);
  assert.match(contentSource, /request\.action === 'apply_settings'/);
  assert.match(contentSource, /currentSettings = normalizeSettings\(request\.payload\)/);
  assert.match(contentSource, /injectSVGFilter\(\);[\s\S]*startVideoObservers\(\);[\s\S]*updateVideoFilters\(\)/);
});

test('English UI strings do not contain CJK characters', () => {
  const enBlock = i18nMessagesSource.slice(
    i18nMessagesSource.indexOf('export const enMessages = {'),
    i18nMessagesSource.indexOf('export type Messages = typeof enMessages;'),
  );
  const localeNameBlock = i18nMessagesSource.slice(
    i18nMessagesSource.indexOf('export const localeNames'),
    i18nMessagesSource.indexOf('export const enMessages'),
  );

  assert.doesNotMatch(enBlock, /[\u3040-\u30ff\u3400-\u9fff]/);
  assert.doesNotMatch(localeNameBlock, /[\u3040-\u30ff\u3400-\u9fff]/);
  assert.match(i18nMessagesSource, /Traditional Chinese/);
  assert.match(i18nMessagesSource, /Simplified Chinese/);
  assert.match(i18nMessagesSource, /Japanese/);
  assert.match(i18nMessagesSource, /localeShortNames/);
  assert.doesNotMatch(i18nMessagesSource, /calibratedSimulation/);
});

test('design docs describe the signal path workflow and standalone diagnostics boundary', () => {
  assert.match(designSource, /Signal Path Console/);
  assert.match(designSource, /detail shaping, perceptual transfer, levels, color, then dither/);
  assert.match(designSource, /does not expose camera luminance estimation or element picking/);
  assert.match(designSource, /standalone route as a rough visual meter/);
  assert.match(designSource, /rough estimates/);
  assert.match(designSource, /browser's native side panel by default/);
  assert.match(designSource, /pinned reference strip/);
  assert.match(designSource, /complete Dither controls inside the terminal quantization stage/);
  assert.match(designSource, /visually attached diagnostic branch/);
  assert.match(designZhTwSource, /Signal Path Console/);
  assert.match(designZhTwSource, /細節整形、感知轉換、Levels、色彩，最後 Dither/);
  assert.match(designZhTwSource, /刻意不提供相機亮度估算與元素選取/);
  assert.match(designZhTwSource, /只保留在獨立路由/);
  assert.match(designZhTwSource, /粗略估計/);
  assert.match(designZhTwSource, /瀏覽器原生側邊欄開啟/);
  assert.match(designZhTwSource, /固定參考帶/);
  assert.match(designZhTwSource, /完整 Dither 控制直接放入終端量化階段/);
  assert.match(designZhTwSource, /附掛的診斷分支/);
  assert.doesNotMatch(designSource, /A, B, and C|compact, split, and expanded work modes/);
  assert.doesNotMatch(designZhTwSource, /A、B、C|精簡、左右分欄、完整展開模式/);
});

test('i18n supports system language detection and persisted language preference', () => {
  assert.match(i18nMessagesSource, /supportedLocales = \['en', 'zh-TW', 'zh-CN', 'ja'\]/);
  assert.match(i18nIndexSource, /LANGUAGE_STORAGE_KEY = 'gsdf_language'/);
  assert.match(i18nIndexSource, /navigator\.languages/);
  assert.match(i18nIndexSource, /resolveSystemLocale/);
  assert.match(i18nIndexSource, /zh-hant/);
  assert.match(i18nIndexSource, /zh-hans/);
  assert.match(appSource, /getInitialLocale/);
  assert.match(appSource, /handleLocaleChange/);
  assert.match(panelSource, /LanguageSelector/);
  assert.match(panelSource, /supportedLocales\.map/);
  assert.match(i18nLocalesSource, /export const zhTwMessages: Messages =/);
  assert.match(i18nLocalesSource, /export const zhCnMessages: Messages =/);
  assert.match(i18nLocalesSource, /export const jaMessages: Messages =/);
  assert.match(i18nMessagesSource, /title: 'Camera luminance probe'/);
  assert.match(i18nMessagesSource, /roughMeterBoundary/);
  assert.match(i18nMessagesSource, /Start camera probe/);
  assert.match(i18nLocalesSource, /相機亮度偵測/);
});

test('standalone video preview uses the shared active transfer table model', () => {
  assert.match(videoBackgroundSource, /buildActiveTransferTableValues\(settings\)/);
  assert.match(videoBackgroundSource, /tableValues=\{transferTableValues\}/);
  assert.match(videoBackgroundSource, /settings\.transferFormula === 'csdf'/);
  assert.match(videoBackgroundSource, /settings\.gsdfPipeline === 'rgb'/);
  assert.match(videoBackgroundSource, /id="eotf-gsdf-rgb"/);
  assert.match(videoBackgroundSource, /id="eotf-gsdf-ycbcr"/);
  assert.match(videoBackgroundSource, /id="eotf-csdf"/);
  assert.match(videoBackgroundSource, /buildLumaChromaMatrices\(settings\.displayGamut\)/);
  assert.match(videoBackgroundSource, /<feFuncR type="table" tableValues=\{transferTableValues\} \/>/);
  assert.match(videoBackgroundSource, /<feFuncG type="table" tableValues=\{transferTableValues\} \/>/);
  assert.match(videoBackgroundSource, /<feFuncB type="table" tableValues=\{transferTableValues\} \/>/);
  assert.doesNotMatch(videoBackgroundSource, /result="csdf-ycc"/);
  assert.doesNotMatch(videoBackgroundSource, /in="csdf-adjusted"/);
  assert.match(videoBackgroundSource, /eotf-color/);
  assert.match(videoBackgroundSource, /hueRotate/);
  assert.match(videoBackgroundSource, /settings\.saturation/);
  assert.match(videoBackgroundSource, /settings\.grayscale/);
  assert.match(videoBackgroundSource, /settings\.dither/);
  assert.match(videoBackgroundSource, /settings\.ditherStrength/);
  assert.match(videoBackgroundSource, /settings\.ditherColor/);
  assert.match(videoBackgroundSource, /settings\.ditherNoise/);
  assert.match(videoBackgroundSource, /settings\.fineSharpness/);
  assert.match(videoBackgroundSource, /settings\.mediumSharpness/);
  assert.match(videoBackgroundSource, /id="eotf-dither"/);
  assert.match(videoBackgroundSource, /<feTurbulence type="fractalNoise"/);
  assert.match(videoBackgroundSource, /ditherNoiseComposite/);
  assert.match(videoBackgroundSource, /ditherColorComposite/);
  assert.match(videoBackgroundSource, /\$\{ditherFilter\}/);
  assert.match(videoBackgroundSource, /TONE_LEVEL_COUNT/);
  assert.match(videoBackgroundSource, /\$\{transferFilter\} url\(#eotf-levels\)/);
  assert.doesNotMatch(videoBackgroundSource, /url\(#eotf-levels\) \$\{transferFilter\}/);
  assert.doesNotMatch(videoBackgroundSource, /settings\.colorModel/);
  assert.doesNotMatch(videoBackgroundSource, /type="gamma"/);
});
